### ISSUE TITLE
Provide type definitions for TypeScript developers

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [evrythng/epcis2.js#14]
It would be good to provide TypeScript type definitions to facilitate development using TypeScript

**Comment by clementh59** [comment]
Hi José, this is a good idea indeed. 
For now, this is not the priority since we are focused on delivering a version that reflects all updates to the standard. However, we'll keep that in mind for later.
But you are of course welcome to make a PR if you think it wouldn't require a lot of resources. 😁

**Comment by clementh59** [comment]
Hi José, the package is now typescript compatible.
The types are available here: https://www.npmjs.com/package/@types/epcis2.js

Cheers,
Clément
